version: "3.9"
services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/project
        environment: 
            PORT: 8000
            FLASK_DEBUG: 1
            
