openapi: 3.0.3
info:
  title: "Visitors Database"
  description: "An API about people and notes"
  version: "1.1.0"

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - surname
      properties:
        name:
          type: "string"
        surname:
          type: "string"
  parameters:
    surname:
      name: "surname"
      description: "Last name of the person to get"
      in: path
      required: True
      schema:
        type: "string"


paths:
  /database:
    get:
      operationId: "database.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"
    post:
      operationId: "database.create"
      tags:
        - People
      summary: "Create a person"
      requestBody:
          description: "Person to create"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "person"
                $ref: "#/components/schemas/Person"
      responses:
        "201":
          description: "Successfully created person"


  /database/{surname}:
    get:
      operationId: "database.read_one"
      tags:
        - People
      summary: "Read one person based on surname"
      parameters:
        - $ref: "#/components/parameters/surname"
      responses:
        "200":
          description: "Successfully read person"

    
    put:
      tags:
        - People
      operationId: "database.update"
      summary: "Update a person"
      parameters:
        - $ref: "#/components/parameters/surname"
      responses:
        "200":
          description: "Successfully updated person"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"

    delete:
      tags:
        - People
      operationId: "database.delete"
      summary: "Delete a person"
      parameters:
        - $ref: "#/components/parameters/surname"
      responses:
        "204":
          description: "Successfully deleted person"



