name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v3
          
    - name: Docker Info
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Build
      run: docker build -t ${{ secrets.DOCKER_USER }}/flask-api:latest .
    - name: Upload container to Docker Hub with Push
      run: docker push ${{ secrets.DOCKER_USER }}/flask-api:latest
